# Generated by Django 5.2.8 on 2025-11-25 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название пункта')),
                ('slug', models.SlugField(max_length=150, unique=True, verbose_name='Слаг пункта')),
                ('menu_name', models.CharField(max_length=50, verbose_name='Название меню')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='tree_menu.menupoint', verbose_name='Родительский пункт')),
            ],
            options={
                'verbose_name': 'Пункт меню',
                'verbose_name_plural': 'Пункты меню',
                'indexes': [models.Index(fields=['menu_name'], name='tree_menu_m_menu_na_1a0a50_idx')],
            },
        ),
    ]
