# Generated by Django 5.2.8 on 2025-11-26 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree_menu', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menupoint',
            name='slug',
        ),
        migrations.AddField(
            model_name='menupoint',
            name='named_url',
            field=models.CharField(blank=True, max_length=100, verbose_name='Имя URL из urls.py'),
        ),
        migrations.AddField(
            model_name='menupoint',
            name='url',
            field=models.CharField(blank=True, max_length=200, verbose_name='URL явный'),
        ),
    ]
